version: '3.7'

services:
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db
    restart: on-failure
  item-app:
    image: item-app:v1
    #command: sh -c "yarn install & yarn run dev"
    ports:
      - 8081:8080
    working_dir: /app
    environment:
      NODE_ENV: production
      DB_HOST: item-db
    restart: on-failure
volumes:
  app-db:
